[package]
name = "giga"
version = "0.5.0"
edition = "2021"
homepage = "https://github.com/ecks0/giga"
license = "MIT"
authors = ["eckso <eckso@eckso.io>"]

[features]
default = []
logging = ["log", "nix"]

[dependencies]
async-trait = "~0.1"
log = { version = "~0.4", optional = true }
nix = { version = "~0.23", optional = true }
nvml-wrapper = { version = "~0.7" }
once_cell = "1.8.0"
serde = { version = "~1.0", features = ["derive"], optional = true }
thiserror = "~1.0"

[dependencies.tokio]
version = "~1.14"
default-features = false
features = [
  "fs",
  "io-util",
  "parking_lot",
  "rt",
  "sync",
  "time",
]
