[package]
name = "giga"
version = "0.5.0"
edition = "2021"
homepage = "https://github.com/ecks0/giga"
license = "MIT"
authors = ["eckso <eckso@eckso.io>"]

[features]
default = []
logging = ["log", "nix"]
sync = []

[dependencies]
log = { version = "~0.4", optional = true }
nix = { version = "~0.23", optional = true }
nvml-wrapper = "~0.7"
once_cell = "1.8.0"
parking_lot = "0.11.2"
thiserror = "~1.0"

[dependencies.tokio]
version = "~1.14"
default-features = false
features = [
  "fs",
  "io-util",
  "macros",
  "parking_lot",
  "rt",
  "sync",
  "time",
]
